apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: silence-manager
rules:
# Required for Alertmanager service discovery across all namespaces
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
